root = "."
tmp_dir = "bin"

[build]
  cmd = "go build -o ./bin/cyphera-api-dev ./cmd/api/local/main.go"
  bin = "./bin/cyphera-api-dev"
  delay = 500 # in milliseconds
  exclude_dir = ["assets", "tmp", "bin", "vendor", "node_modules", "delegation-server"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_regex = ["_test\\.go"]
  kill_delay = "0s"
  send_interrupt = true

[log]
  time = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"