root = "."
tmp_dir = "bin"

[build]
  cmd = "go build -o bin/cyphera-api ./cmd/api/main.go"
  bin = "./bin/cyphera-api"
  delay = 500 # in milliseconds
  exclude_dir = ["assets", "tmp", "bin", "vendor"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_regex = ["_test\\.go"]

[log]
  time = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"