version: "2"
linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - bodyclose
    - goconst
    - goimports
run:
  timeout: 5m

# Add linter-specific settings
linters-settings:
  goconst:
    # Minimum number of occurrences for goconst to report
    min-occurrences: 6

# Add this section to ignore issues
issues:
  exclude-rules:
    # Rule for test files
    - path: _test\.go$ # Regex matching files ending with _test.go
      linters:
        # List linters to disable for test files
        - gocyclo  # Ignore complexity warnings in tests
        - funlen   # Ignore function length warnings in tests
        - goconst  # Ignore constant string duplication warnings in tests (redundant if min-occurrences is high)
        - unused  # Ignore unused variables in tests
        - errcheck  # Ignore errors in tests
        # - errcheck # Example: Uncomment if you want to ignore unchecked errors in tests
        # Add any other linters you want to ignore specifically for test files