linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    #- ineffassign
    - misspell
    # - bodyclose
    - goconst
    - goimports
  settings:
    goconst:
      min-occurrences: 6
run:
  timeout: 5m