services:
  # cyphera-api:
  #   build: .
  #   container_name: cyphera-api
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - NODE_ENV=development
  #     - DATABASE_URL=${DATABASE_URL}
  #     - ACTALINK_API_KEY=${ACTALINK_API_KEY}
  #     - PORT=8000
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   volumes:
  #     - ./:/usr/src/app
  #     - /usr/src/app/node_modules
  #   networks:
  #     - cyphera-network

  postgres:
    container_name: cyphera-db
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=apiuser
      - POSTGRES_PASSWORD=apipassword
      - POSTGRES_DB=cyphera
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./internal/db/init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U apiuser -d cyphera"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - cyphera-network

volumes:
  postgres_data:

networks:
  cyphera-network:
    driver: bridge 