service: cyphera-api

frameworkVersion: '3'

plugins:
  - serverless-domain-manager

provider:
  name: aws
  runtime: provided.al2
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  httpApi:
    payload: '1.0'
    cors: true
    metrics: true
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    AUTH0_DOMAIN: ${env:AUTH0_DOMAIN}
    AUTH0_AUDIENCE: ${env:AUTH0_AUDIENCE}
  vpc:
    securityGroupIds:
      - ${ssm:/cyphera/lambda-security-group-id}
    subnetIds:
      - ${ssm:/cyphera/private-subnet-1}
      - ${ssm:/cyphera/private-subnet-2}

custom:
  customDomain:
    domainName: ${self:provider.stage}.api.cypherapay.com
    certificateArn: ${ssm:/cyphera/wildcard-api-cert-arn}
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: false
    endpointType: regional
    securityPolicy: TLS_1_2
    apiType: http
    autoDomain: true
  vpc:
    local:
      securityGroupIds: []
      subnetIds: []
    prod:
      securityGroupIds:
        - ${ssm:/cyphera/lambda-security-group-id, ''}
      subnetIds:
        - ${ssm:/cyphera/private-subnet-1, ''}
        - ${ssm:/cyphera/private-subnet-2, ''}

functions:
  main:
    handler: bootstrap
    events:
      - httpApi:
          path: /health
          method: GET
      - httpApi:
          path: /{proxy+}
          method: ANY
    timeout: 29
    memorySize: 256
    environment:
      GIN_MODE: release