service: cyphera-api

frameworkVersion: '3'

plugins:
  - serverless-domain-manager

provider:
  name: aws
  runtime: provided.al2
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  httpApi:
    payload: '1.0'
    cors: true
    metrics: true
  environment:
    SUPABASE_URL: ${env:SUPABASE_URL}
    SUPABASE_JWT_SECRET: ${env:SUPABASE_JWT_SECRET}
    CORS_ALLOWED_ORIGINS: ${env:CORS_ALLOWED_ORIGINS}
    CORS_ALLOWED_METHODS: ${env:CORS_ALLOWED_METHODS}
    CORS_ALLOWED_HEADERS: ${env:CORS_ALLOWED_HEADERS}
    CORS_EXPOSED_HEADERS: ${env:CORS_EXPOSED_HEADERS}
    CORS_ALLOW_CREDENTIALS: ${env:CORS_ALLOW_CREDENTIALS}
    GIN_MODE: release
    DELEGATION_SERVER_URL: ${ssm:/cyphera/delegation-server-alb-dns-${self:provider.stage}}:50051
    
    RDS_SECRET_ARN: ${ssm:/cyphera/rds-secret-arn-${self:provider.stage}}
    DB_HOST: ${ssm:/cyphera/rds-endpoint-${self:provider.stage}}
    DB_NAME: cyphera
    DB_PORT: 5432
    DB_SSLMODE: require
    CYPHERA_SMART_WALLET_ADDRESS: ${env:CYPHERA_SMART_WALLET_ADDRESS}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
          Resource:
            - ${ssm:/cyphera/rds-secret-arn-${self:provider.stage}}
        - Effect: "Allow"
          Action:
            - "ec2:CreateNetworkInterface"
            - "ec2:DescribeNetworkInterfaces"
            - "ec2:DeleteNetworkInterface"
          Resource: "*"
        - Effect: "Allow"
          Action:
            - "logs:CreateLogGroup"
            - "logs:CreateLogStream"
            - "logs:PutLogEvents"
          Resource: "arn:aws:logs:*:*:*"

  vpc:
    securityGroupIds:
      - ${ssm:/cyphera/lambda-security-group-id}
    subnetIds:
      - ${ssm:/cyphera/private-subnet-1}
      - ${ssm:/cyphera/private-subnet-2}

custom:
  customDomain:
    domainName: ${self:provider.stage}.api.cypherapay.com
    certificateArn: ${ssm:/cyphera/wildcard-api-cert-arn}
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: false
    endpointType: regional
    securityPolicy: TLS_1_2
    apiType: http
    autoDomain: true

functions:
  main:
    handler: bootstrap
    events:
      - httpApi:
          path: /health
          method: GET
      - httpApi:
          path: /{proxy+}
          method: ANY
    timeout: 29
    memorySize: 256