service: cyphera-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: provided.al2
  region: us-east-1
  httpApi:
    payload: '1.0'
    cors: true
    metrics: true
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    ACTALINK_API_KEY: ${env:ACTALINK_API_KEY}
    AUTH0_DOMAIN: ${env:AUTH0_DOMAIN}
    AUTH0_AUDIENCE: ${env:AUTH0_AUDIENCE}
  vpc:
    securityGroupIds:
      - ${ssm:/cyphera/lambda-security-group-id}
    subnetIds:
      - ${ssm:/cyphera/private-subnet-1}
      - ${ssm:/cyphera/private-subnet-2}

custom:
  vpc:
    local:
      securityGroupIds: []
      subnetIds: []
    prod:
      securityGroupIds:
        - ${ssm:/cyphera/lambda-security-group-id, ''}
      subnetIds:
        - ${ssm:/cyphera/private-subnet-1, ''}
        - ${ssm:/cyphera/private-subnet-2, ''}

functions:
  main:
    handler: bootstrap
    events:
      - httpApi:
          path: /health
          method: GET
      - httpApi:
          path: /{proxy+}
          method: ANY
    timeout: 29
    memorySize: 256
    environment:
      GIN_MODE: release

resources:
  Resources:
    ApiGatewayDomainName:
      Type: AWS::ApiGatewayV2::DomainName
      Properties:
        DomainName: api.cypherapay.com
        DomainNameConfigurations:
          - CertificateArn: arn:aws:acm:us-east-1:699475955358:certificate/2aab5f4d-bc62-42de-83b2-74d61ef8d0c2
            EndpointType: REGIONAL
            SecurityPolicy: TLS_1_2
    ApiGatewayMapping:
      Type: AWS::ApiGatewayV2::ApiMapping
      Properties:
        DomainName: api.cypherapay.com
        ApiId: ${aws:ApiGatewayRestApi}
        Stage: $default
        ApiMappingKey: dev