service: cyphera-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: provided.al2
  region: us-east-1
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    ACTALINK_API_KEY: ${env:ACTALINK_API_KEY}
    AUTH0_DOMAIN: ${env:AUTH0_DOMAIN}
    AUTH0_AUDIENCE: ${env:AUTH0_AUDIENCE}
  vpc:
    securityGroupIds:
      - ${ssm:/cyphera/lambda-security-group-id}
    subnetIds:
      - ${ssm:/cyphera/private-subnet-1}
      - ${ssm:/cyphera/private-subnet-2}

custom:
  vpc:
    local:
      securityGroupIds: []
      subnetIds: []
    prod:
      securityGroupIds:
        - ${ssm:/cyphera/lambda-security-group-id, ''}
      subnetIds:
        - ${ssm:/cyphera/private-subnet-1, ''}
        - ${ssm:/cyphera/private-subnet-2, ''}

functions:
  api:
    handler: bootstrap
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY
    timeout: 29
    memorySize: 256