service: cyphera-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: provided.al2
  region: us-east-1
  httpApi:
    payload: '1.0'
  environment:
    ACTALINK_API_KEY : cxiaitiqbnpvbrgaamevrghjojaagxuu
    DATABASE_URL: postgresql://apiuser:apipassword@cyphera-db.cjwqc0yo6vzw.us-east-1.rds.amazonaws.com:5432/cyphera
    AUTH0_DOMAIN: your-tenant.auth0.com
    AUTH0_AUDIENCE: https://api.cyphera.com
  vpc:
    securityGroupIds:
      - ${ssm:/cyphera/lambda-security-group-id}
    subnetIds:
      - ${ssm:/cyphera/private-subnet-1}
      - ${ssm:/cyphera/private-subnet-2}

custom:
  vpc:
    local:
      securityGroupIds: []
      subnetIds: []
    prod:
      securityGroupIds:
        - ${ssm:/cyphera/lambda-security-group-id, ''}
      subnetIds:
        - ${ssm:/cyphera/private-subnet-1, ''}
        - ${ssm:/cyphera/private-subnet-2, ''}

functions:
  main:
    handler: bootstrap
    events:
      - httpApi:
          path: /health
          method: GET
      - httpApi:
          path: /{proxy+}
          method: ANY
    timeout: 29
    memorySize: 256
    environment:
      GIN_MODE: release