AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Dunning Processor Lambda - Processes dunning campaigns and sends recovery emails

Parameters:
  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Deployment stage

  DBHost:
    Type: String
    Description: Database host endpoint

  DBName:
    Type: String
    Default: cypheradb
    Description: Database name

  RDSSecretArn:
    Type: String
    Description: ARN of the RDS secret in Secrets Manager

  ResendAPIKeyArn:
    Type: String
    Description: ARN of the Resend API key secret in Secrets Manager

  DunningFromEmail:
    Type: String
    Default: noreply@cypherapay.com
    Description: From email address for dunning emails

  DunningFromName:
    Type: String
    Default: Cyphera
    Description: From name for dunning emails

  VpcSubnetIds:
    Type: CommaDelimitedList
    Description: Comma-delimited list of subnet IDs for Lambda VPC configuration

  VpcSecurityGroupIds:
    Type: CommaDelimitedList
    Description: Comma-delimited list of security group IDs for Lambda VPC configuration

  ScheduleExpression:
    Type: String
    Default: rate(5 minutes)
    Description: Schedule expression for running the dunning processor (dev=5min, prod=1min)

Globals:
  Function:
    Timeout: 300
    MemorySize: 512
    Runtime: provided.al2
    Architectures:
      - x86_64
    Environment:
      Variables:
        STAGE: !Ref Stage
        DB_HOST: !Ref DBHost
        DB_NAME: !Ref DBName
        RDS_SECRET_ARN: !Ref RDSSecretArn
        RESEND_API_KEY_ARN: !Ref ResendAPIKeyArn
        DUNNING_FROM_EMAIL: !Ref DunningFromEmail
        DUNNING_FROM_NAME: !Ref DunningFromName
        DB_SSLMODE: require

Resources:
  DunningProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-${Stage}
      CodeUri: ../../apps/dunning-processor/bin/
      Handler: bootstrap
      Description: Processes dunning campaigns and sends recovery emails
      VpcConfig:
        SubnetIds: !Ref VpcSubnetIds
        SecurityGroupIds: !Ref VpcSecurityGroupIds
      Policies:
        - AWSLambdaVPCAccessExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource:
                - !Ref RDSSecretArn
                - !Ref ResendAPIKeyArn
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: '*'
            - Effect: Allow
              Action:
                - cloudwatch:PutMetricData
              Resource: '*'
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: !Ref ScheduleExpression
            Description: Trigger dunning processor on schedule
            Enabled: true

  DunningProcessorLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${DunningProcessorFunction}
      RetentionInDays: 30

  # CloudWatch Alarms
  DunningProcessorErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${AWS::StackName}-${Stage}-errors
      AlarmDescription: Alert when dunning processor has errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref DunningProcessorFunction
      TreatMissingData: notBreaching

  DunningProcessorThrottleAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${AWS::StackName}-${Stage}-throttles
      AlarmDescription: Alert when dunning processor is throttled
      MetricName: Throttles
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref DunningProcessorFunction
      TreatMissingData: notBreaching

Outputs:
  DunningProcessorFunctionName:
    Description: Dunning Processor Lambda function name
    Value: !Ref DunningProcessorFunction

  DunningProcessorFunctionArn:
    Description: Dunning Processor Lambda function ARN
    Value: !GetAtt DunningProcessorFunction.Arn

  DunningProcessorLogGroup:
    Description: CloudWatch Logs group for Dunning Processor
    Value: !Ref DunningProcessorLogGroup