// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	DeactivateAPIKey(ctx context.Context, id uuid.UUID) error
	DeleteCustomer(ctx context.Context, id uuid.UUID) error
	GetAPIKey(ctx context.Context, id uuid.UUID) (ApiKey, error)
	GetAPIKeyByHash(ctx context.Context, keyHash string) (ApiKey, error)
	GetCustomer(ctx context.Context, id uuid.UUID) (Customer, error)
	ListAPIKeys(ctx context.Context, customerID pgtype.UUID) ([]ApiKey, error)
	ListCustomers(ctx context.Context) ([]Customer, error)
	UpdateAPIKeyLastUsed(ctx context.Context, id uuid.UUID) error
	UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error)
}

var _ Querier = (*Queries)(nil)
