// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error)
	DeleteAPIKey(ctx context.Context, id uuid.UUID) error
	DeleteAccount(ctx context.Context, id uuid.UUID) error
	DeleteCustomer(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DeleteWorkspace(ctx context.Context, id uuid.UUID) error
	GetAPIKey(ctx context.Context, id uuid.UUID) (ApiKey, error)
	GetAPIKeyByKey(ctx context.Context, keyHash string) (ApiKey, error)
	GetAccount(ctx context.Context, id uuid.UUID) (Account, error)
	GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error)
	GetAccountByWorkspaceID(ctx context.Context, id uuid.UUID) (Account, error)
	GetAccountOwner(ctx context.Context, accountID uuid.UUID) (User, error)
	GetAccountUsers(ctx context.Context, accountID uuid.UUID) ([]GetAccountUsersRow, error)
	GetActiveAPIKeysCount(ctx context.Context, workspaceID uuid.UUID) (int64, error)
	GetAllAPIKeys(ctx context.Context) ([]ApiKey, error)
	GetAllAccounts(ctx context.Context) ([]Account, error)
	GetAllCustomers(ctx context.Context) ([]Customer, error)
	GetAllWorkspaces(ctx context.Context) ([]Workspace, error)
	GetCustomer(ctx context.Context, id uuid.UUID) (Customer, error)
	GetCustomerByEmail(ctx context.Context, arg GetCustomerByEmailParams) (Customer, error)
	GetCustomerByExternalID(ctx context.Context, arg GetCustomerByExternalIDParams) (Customer, error)
	GetCustomersByBalance(ctx context.Context, arg GetCustomersByBalanceParams) ([]Customer, error)
	GetCustomersWithWorkspaceInfo(ctx context.Context, workspaceID uuid.UUID) ([]GetCustomersWithWorkspaceInfoRow, error)
	GetExpiredAPIKeys(ctx context.Context) ([]ApiKey, error)
	GetUserAccount(ctx context.Context, id uuid.UUID) (GetUserAccountRow, error)
	GetUserByAuth0ID(ctx context.Context, auth0ID string) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetWorkspace(ctx context.Context, id uuid.UUID) (Workspace, error)
	HardDeleteAccount(ctx context.Context, id uuid.UUID) error
	HardDeleteWorkspace(ctx context.Context, id uuid.UUID) error
	ListAPIKeys(ctx context.Context, workspaceID uuid.UUID) ([]ApiKey, error)
	ListAccounts(ctx context.Context) ([]Account, error)
	ListAccountsByType(ctx context.Context, accountType AccountType) ([]Account, error)
	ListAccountsByUser(ctx context.Context, id uuid.UUID) ([]Account, error)
	ListCustomers(ctx context.Context, workspaceID uuid.UUID) ([]Customer, error)
	ListUsersByAccount(ctx context.Context, accountID uuid.UUID) ([]User, error)
	ListWorkspaceCustomers(ctx context.Context, id uuid.UUID) ([]Customer, error)
	ListWorkspaces(ctx context.Context) ([]Workspace, error)
	ListWorkspacesByAccountID(ctx context.Context, accountID uuid.UUID) ([]Workspace, error)
	SearchAccounts(ctx context.Context, arg SearchAccountsParams) ([]Account, error)
	UpdateAPIKey(ctx context.Context, arg UpdateAPIKeyParams) (ApiKey, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error)
	UpdateCustomerBalance(ctx context.Context, arg UpdateCustomerBalanceParams) (Customer, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error)
	UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error)
}

var _ Querier = (*Queries)(nil)
