name: Cyphera Subscription Processor CI/CD

on:
  push:
    branches: [ dev, main ]
    paths: # Trigger more specifically
      - 'cmd/subscription-processor/**'
      - 'internal/client/delegation_server/**'
      - 'internal/proto/**'
      - 'internal/**' # Trigger on shared internal changes
      - 'go.mod'
      - 'go.sum'
      - 'Makefile'
      - 'deployment/template-subprocessor.yaml'
      - '.github/workflows/subscription-processor.yml'
      - 'scripts/deploy_subprocessor.sh'
  pull_request:
    branches: [ dev, main ]
    paths: # Trigger more specifically
      - 'cmd/subscription-processor/**'
      - 'internal/client/delegation_server/**'
      - 'internal/proto/**'
      - 'internal/**' # Trigger on shared internal changes
      - 'go.mod'
      - 'go.sum'
      - 'Makefile'
      - 'deployment/template-subprocessor.yaml'
      - '.github/workflows/subscription-processor.yml'
      - 'scripts/deploy_subprocessor.sh'

env:
  GO_VERSION: '1.23'
  AWS_REGION: us-east-1
  STAGE: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
  TEMPLATE_FILE: deployment/template-subprocessor.yaml

jobs:
  deploy:
    name: Deploy Subscription Processor
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev'
    environment: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}

    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup SAM CLI
      uses: aws-actions/setup-sam@v2
      with:
        use-installer: true

    # SAM Build: Use the specific template and build inside container
    - name: SAM Build for Subscription Processor
      run: sam build --template ${{ env.TEMPLATE_FILE }} --use-container

    - name: Make deployment script executable
      run: chmod +x scripts/deploy_subprocessor.sh

    - name: Run Deployment Script for Subscription Processor
      env:
        STAGE: ${{ env.STAGE }}
        AWS_REGION: ${{ env.AWS_REGION }}
        SAM_DEPLOYMENT_BUCKET: ${{ secrets.SAM_DEPLOYMENT_BUCKET }}
        LAMBDA_SG_ID: ${{ secrets.LAMBDA_SG_ID }}
        PRIVATE_SUBNET_1_ID: ${{ secrets.PRIVATE_SUBNET_1_ID }}
        PRIVATE_SUBNET_2_ID: ${{ secrets.PRIVATE_SUBNET_2_ID }}
        # Pass any other secrets needed by deploy_subprocessor.sh
      run: ./scripts/deploy_subprocessor.sh

    # Optional: Show stack outputs after successful deployment
    # - name: Show SAM Stack Outputs
    #   if: success()
    #   run: aws cloudformation describe-stacks --stack-name cyphera-subprocessor-${{ env.STAGE }} --query 'Stacks[0].Outputs' --region ${{ env.AWS_REGION }} 